source 'https://github.com/CocoaPods/Specs.git'

target 'CLCBannerNotifications_Example', :exclusive => true do
  pod "CLCBannerNotifications", :path => "../CLCBannerNotifications.podspec"
end

target 'CLCBannerNotifications_Tests', :exclusive => true do
  pod "CLCBannerNotifications", :path => "../CLCBannerNotifications.podspec"
  
end
